---
title: "eggSim"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{eggSim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library("tidyverse")
library("eggSim")
```

```{r}

budget <- 600
reduction <- 0.05

# Decide on variability partitions:
cv_between <- 1.5
cv_within <- 0.75
cv_slide <- 0.25
cv_reduction <- 0
# Overall k is about 0.23 - seems sensible??
combined_k(cv_between, cv_within, cv_slide, cv_reduction)

# Simulate data:
simdatagp <- cgpDataSim(R=10^3, N=budget, reduction=reduction, community_mean=24, cv_between=cv_between, cv_within=cv_within, cv_slide=cv_slide, cv_reduction=cv_reduction, grams=1/24)

gpmeans <- design_means(simdatagp, budget=budget, count=TRUE)

comnrs <- gpmeans %>%
  count(Design, Communities)
ggplot(comnrs, aes(x=Design, y=n, fill=factor(Communities))) +
  geom_col()

ggplot(gpmeans %>% filter(Communities > 0), aes(x=Design, y=ScreenProp)) +
  geom_boxplot()

ggplot(gpmeans %>% filter(Communities > 0), aes(x=Design, y=ArithmeticEfficacy)) +
  geom_hline(yintercept=100*(1-reduction)) +
  geom_boxplot()

ggplot(gpmeans %>% filter(Communities > 0), aes(x=ArithmeticEfficacy, col=Design)) +
  stat_ecdf()

gpmeans %>%
  mutate(Success = 100 * sum(Communities > 0) / n()) %>%
  filter(Communities > 0) %>%
  group_by(Design, Success) %>%
  summarise(ScreenProp = mean(ScreenProp), Mean = mean(ArithmeticEfficacy), Median = median(ArithmeticEfficacy), Variance = var(ArithmeticEfficacy), .groups='drop')
```

